### ISSUE TITLE
shift_right doesn't work as expected on BlinkStickProMatrix

### ISSUE THREAD

**Issue by soerennb** [arvydas/blinkstick-python#31]
I'm trying to use shift_right() to move lights formed as an arrow on my NeoMatrix, but it doesn't work as expected. Regardless if I set the "Remove" argument as true or false, the pixels don't  re-appear on the left side of the matrix.
Interestingly the shift_left() function works like it should (pixels re-appear on the right), so I guess there's a bug in the shift_right function, but my matrix programming skills are not good enough to debug the function.

**Comment by arvydas** [comment]
I reproduced this. Working on a fix now.

**Comment by arvydas** [comment]
This is now fixed in the repository. Other matrix shift functions also had issues. I tested and fixed all of them in remove and non remove modes.
