### ISSUE TITLE
Blinksquare not working on Raspberry Pi

### ISSUE THREAD

**Issue by ariestar** [arvydas/blinkstick-python#39]
Hi @arvydas,

I hope you are well. Thanks for the prompt delivery and personal note :) Always a pleasure.
I can't get the blinksquare to work on Raspberry Pi.. all is default, no error, no nothing..
pip installed without a problem, dmesg doesn't display anything.. any idea?
It works fine on Windows with the client.

Thanks, hope to hear from you soon.

**Comment by ariestar** [comment]
Forgot to mention.. the old blinkstick I have modified and put inside the globe works fine.. so something is new with the blinksquare that's not recognised by the kernel

**Comment by ariestar** [comment]
Ahh.. don't worry about it.. faulty cable is to blame :) Love the small cube

**Comment by arvydas** [comment]
Glad to hear you like BlinkStick and got this sorted out :)
