### ISSUE TITLE
Blinkstick Nano turn off led 1 (bottom)

### ISSUE THREAD

**Issue by rickpeters** [arvydas/blinkstick-python#65]
I can use led 1 and led 0 om my blinkstick nano, however I cannot find a way to use turn_off() on led 1. I tried looping through leds with find_all() but this only finds led 0.
Am I missing something?

**Comment by arvydas** [comment]
Just send color #000000 black to the channel and it will turn it off.

**Comment by rickpeters** [comment]
stupid me 😂 works like a charm, why didn't I think of that. Thanks very much for the quick reply 👍
